name: pks1424-jet-modeling

channels:
  - conda-forge

dependencies:
  - python=3.12
  - pip

  - pip:
      - --upgrade pip setuptools wheel
      - numpy>=1.26.4,<2.0
      - scipy>=1.14.0
      - matplotlib>=3.8.0
      - sympy==1.12
      - lmfit==1.2.2
      - emcee==3.1.4
      - corner==2.2.1
