name: pks1424-jet-modeling
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7.*
  - pip
  - numpy>=1.21.0
  - scipy>=1.7.0
  - matplotlib>=3.5.0
  - jupyter>=1.0.0
  - ipykernel>=6.0.0
  - sympy>=1.8.0
  - lmfit>=1.0.0
  - emcee>=4.0.0
  - corner>=2.0.1
  - nb_conda_kernels>=2.3.0

  - pip
  - pip:
    - numpy==1.21.6
    - matplotlib==3.5.3
    - scipy==1.7.3
    - emcee==3.1.4
    - corner==2.2.1
    - sympy==1.10.1
    - lmfit==1.2.2
    - jupyter==>=1.0.0
    - ipykernel==6.16.2
    - nb_conda_kernels==>=2.3.0
